# Generated by Django 5.1.7 on 2025-03-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capston_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Inventory_item',
        ),
    ]
